name: campus_quest
description: "A gamified social quest app for college students."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  camera: ^0.11.2
  image_picker: ^1.1.2
  image: ^4.1.7
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.4.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  http_parser: ^4.1.2
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "assets/compact_logo.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/adaptive_background.png"
  adaptive_icon_foreground: "assets/adaptive_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/full_logo.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Anuphan
      fonts:
        - asset: assets/fonts/Anuphan/Anuphan-VariableFont_wght.ttf

